controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    my_controller:
      type: controller_interface/ControllerInterface

franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda

model_example_controller:
  ros__parameters:
    arm_id: panda

joint_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      panda_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      panda_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      panda_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      panda_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      panda_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      panda_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      panda_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

action_ns: follow_joint_trajectory
default: true
